services:
  postgres:
    image: postgres:16
    container_name: smartfleet-postgres
    environment:
      POSTGRES_DB: smartfleet
      POSTGRES_USER: smartfleet
      POSTGRES_PASSWORD: devpassword123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: smartfleet-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartfleet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres


  mongo:
    image: mongo:7
    container_name: smartfleet-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartfleet
      MONGO_INITDB_ROOT_PASSWORD: devpassword123
      MONGO_INITDB_DATABASE: smartfleet_telemetry
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7-alpine
    container_name: smartfleet-redis
    command: redis-server --requirepass devpassword123
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  mongodata:
  redisdata: