services:
  postgres:
    image: postgres:16
    container_name: smartfleet-postgres
    environment:
      POSTGRES_DB: smartfleet
      POSTGRES_USER: smartfleet
      POSTGRES_PASSWORD: devpassword123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: smartfleet-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartfleet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mongo:
    image: mongo:7
    container_name: smartfleet-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartfleet
      MONGO_INITDB_ROOT_PASSWORD: devpassword123
      MONGO_INITDB_DATABASE: smartfleet_telemetry
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: smartfleet-mongo-ui
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://smartfleet:devpassword123@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  redis:
    image: redis:7-alpine
    container_name: smartfleet-redis
    command: redis-server --requirepass devpassword123
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: smartfleet-redis-ui
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    depends_on:
      - redis

volumes:
  pgdata:
  mongodata:
  redisdata:
  redisinsight: